### PR TITLE
Add support for array of values

### PR DESCRIPTION
**Pull request by jnwatts**
Found your library while trying to extract parameter from the URI, though eventually I needed to support multiple values for the same parameter (bugzilla uses one hidden input for each bug_id when invoking a CGI script to export bugs). This patch keeps with your existing API:
* Param not found: return undefined
* Param found but no value: return empty string
* Param found, 1 value: return value

And one new case:
* Param found, N values: return array of values

### CODE REVIEW

**Comment by websanova** [comment]
Just pushed version 2 with support for arrays :-)

**Comment by jnwatts** [comment]
Just did a quick test, and it seems that arrays (as I've encountered them) don't work: I see your field[n] method works as tested, but my use case (implicit array in the example) still returns a single value:

https://gist.github.com/jnwatts/884813c53d5bcee8ca06

Doing some more digging, it seems there's no "correct" way to encode an array... but my usecase above is one way that is sometimes used (BugZilla in my case).

**Comment by websanova** [comment]
Hey Josh,

I'm not 100% sure about what the strict rule is. However I just tested in
php for an echo $_GET['field'] and it seems to spit out an array when using
indexes and just the last value with same name but no index.

In the example that's for setting, but not sure if the same idea applies
when getting it from url.

If anything the library should fetch the last value and return "4". Right
now it will return based on the first hit. So that can be a potential error.

Thoughts?

Rob

**Comment by jnwatts** [comment]
Hrm, I think I see what you're saying: you're concerned about producing a
different result than PHP?

While I can understand why PHP (and similarly your lib) handle it this way,
I don't see a reasonable use case where someone intentionally puts multiple
fields of the same name and intends to only the last value to be valid. I
think the existing functionality in PHP is just the result of oversight and
a lack standardization.

**Pull request closed without merging**
