### PR TITLE
AMD module

### LINKED ISSUE #50: Add AMD support
It would be nice to include AMD support.

### PR DESCRIPTION
**Pull request by aripalo**
Fixes #50.

If AMD loader is present (basically when `(typeof define === 'function' && define.amd !== undefined)` is truthy) the script registers itself as _anonymous_ AMD module without polluting global `window`-object or extending `jQuery`.

This means that one can use the script by:
```js
require(['http://example.com/url.min.js'], function(privateJsUrl) {
  console.log(typeof window.url); // -> undefined
  console.log(typeof $.url); // -> undefined
  console.log(typeof privateJsUrl); // -> function
  console.log(privateJsUrl('domain', 'http://foo.bar.example.com')); // -> example.com
});
```

### CODE REVIEW

**Comment by websanova** [comment]
Thx, will take a look at this shortly.

**Comment by websanova** [comment]
Ok, this has been pushed up as v2.4.0

**Comment by websanova** [comment]
Thx, for adding this :-)

**Comment by oytuntez** [comment]
Can't see v2.4: https://github.com/websanova/js-url/releases

Thus bower installs 2.3.1

**Comment by websanova** [comment]
Whoops, sorry. Pushed now.

https://github.com/websanova/js-url/releases/tag/v2.4.0

**Comment by oytuntez** [comment]
Perfect! Pulling it right away. Fresh release, mmmmmm...

**Pull request merged**
